I have given up. Commonjs all the modules to make Jest work.
planswell/pw-uikit pull request #99
Opened 2017-08-28 18:57 UTC by Corvillus

Switch es6 import to commonjs require()

Change export / exports to module.exports

Disable MaskedInput test.

Update to version 0.0.3

2017-08-28 19:03 UTC, olafura requested changes

2017-08-28 19:03 UTC, olafura commented on components/input/tests/index.js
> +// seems to be enzyme / babel related.
Missing link to github issue ;)

2017-08-28 20:25 UTC, olafura approved these changes

2017-08-29 15:46 UTC, maedhr approved these changes

2017-08-29 15:46 UTC, merged